open:
  api:
    title: Alpha Code Course Service API
    version: 1.0.0
    description: SEP project with AlphaCode Course Service API
    serverUrl: ${OPEN_API_SERVERURL:http://localhost:8091}

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    server:
      url: ${OPEN_API_SERVERURL:http://localhost:8091}
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

logging:
  level:
    org:
      springdoc: INFO
      springframework: INFO
      io: INFO

spring:
  devtools:
    restart:
      exclude: site/alphacode/alphacodecourseservice/dto/**
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

    listener:
      simple:
        concurrency: 2          # số thread consumer
        max-concurrency: 5
        acknowledge-mode: auto

grpc:
  server:
    port: ${GRPC_COURSE_SERVICE_PORT}
    address: 0.0.0.0
    security:
      enabled: false  # dùng TLS=true nếu cần
  client:
    alpha-user-service:
      address: static://${GRPC_USER_SERVICE_BASE_URL}:${GRPC_USER_SERVICE_PORT}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  forward-headers-strategy: native
